language: php

env:
  - LARAVEL=6
  - LARAVEL=7
  - LARAVEL=8

php:
  - '7.3'
  - '7.4'
  - 'nightly'

jobs:
  allow_failures:
    - php: 'nightly'

before_script:
  - travis_retry composer self-update
  - composer require laravel/framework ^${LARAVEL}.0

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
